version: "3"

services:
  namenode:
    image: namenode:3.2.1
    container_name: NameNode
    hostname: NameNode
    ports:
      - "50070:50070"
      - "9000:9000"
    volumes:
      - NameNode:/opt/hadoop/dfs/name
      - /tmp:/tmp
    networks:
      - bridge

volumes:
  NameNode:

networks:
  bridge:
